set = "default"
generated = "2025-11-07T20:26:18.853Z"
count = 2

[[fragments]]
id = "0"
category = "INFO"
file = ".cms/default/0.md"
content = """
"""

[[fragments]]
id = "1"
category = "INFO"
file = ".cms/default/1.md"
content = """Emit changes instead, full presence only on join."""
[[fragments.occurrences]]
file = "sockets.py"
line = 51
[[fragments.occurrences]]
file = "views/rooms.py"
line = 38
[[fragments.occurrences]]
file = ".root/backend/v1-01/sockets.py"
line = 51
[[fragments.occurrences]]
file = ".root/backend/v1-01/views/rooms.py"
line = 38

